"""empty message

Revision ID: b5936678f098
Revises: 819936aebc31
Create Date: 2024-04-19 09:49:31.969721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5936678f098'
down_revision = '819936aebc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('character_img')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('planet_img')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('vehicle_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_img', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_img', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_img', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
